<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251129111639 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE question_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, uri VARCHAR(255) NOT NULL, mime_type VARCHAR(255) NOT NULL, alt_text VARCHAR(255) DEFAULT NULL, question_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5AC7B0081E27F6BF ON question_media (question_id)');
        $this->addSql('ALTER TABLE question_media ADD CONSTRAINT FK_5AC7B0081E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE question_media DROP CONSTRAINT FK_5AC7B0081E27F6BF');
        $this->addSql('DROP TABLE question_media');
    }
}
