<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251125222812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, answer_session_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DADD4A25EB264E1 ON answer (answer_session_id)');
        $this->addSql('CREATE TABLE answer_session (id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, questionnaire_id INT NOT NULL, current_question_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98041AA5CE07E8FF ON answer_session (questionnaire_id)');
        $this->addSql('CREATE INDEX IDX_98041AA5A0F35D66 ON answer_session (current_question_id)');
        $this->addSql('CREATE TABLE choice (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(255) NOT NULL, question_id INT DEFAULT NULL, next_question_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1AB5A921E27F6BF ON choice (question_id)');
        $this->addSql('CREATE INDEX IDX_C1AB5A921CF5F25E ON choice (next_question_id)');
        $this->addSql('CREATE TABLE question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, questionnaire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6F7494ECE07E8FF ON question (questionnaire_id)');
        $this->addSql('CREATE TABLE questionnaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, root_question_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7A64DAF3980F4B2 ON questionnaire (root_question_id)');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25EB264E1 FOREIGN KEY (answer_session_id) REFERENCES answer_session (id)');
        $this->addSql('ALTER TABLE answer_session ADD CONSTRAINT FK_98041AA5CE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE answer_session ADD CONSTRAINT FK_98041AA5A0F35D66 FOREIGN KEY (current_question_id) REFERENCES question (id)');
        $this->addSql('ALTER TABLE choice ADD CONSTRAINT FK_C1AB5A921E27F6BF FOREIGN KEY (question_id) REFERENCES question (id)');
        $this->addSql('ALTER TABLE choice ADD CONSTRAINT FK_C1AB5A921CF5F25E FOREIGN KEY (next_question_id) REFERENCES question (id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494ECE07E8FF FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF3980F4B2 FOREIGN KEY (root_question_id) REFERENCES question (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE answer DROP CONSTRAINT FK_DADD4A25EB264E1');
        $this->addSql('ALTER TABLE answer_session DROP CONSTRAINT FK_98041AA5CE07E8FF');
        $this->addSql('ALTER TABLE answer_session DROP CONSTRAINT FK_98041AA5A0F35D66');
        $this->addSql('ALTER TABLE choice DROP CONSTRAINT FK_C1AB5A921E27F6BF');
        $this->addSql('ALTER TABLE choice DROP CONSTRAINT FK_C1AB5A921CF5F25E');
        $this->addSql('ALTER TABLE question DROP CONSTRAINT FK_B6F7494ECE07E8FF');
        $this->addSql('ALTER TABLE questionnaire DROP CONSTRAINT FK_7A64DAF3980F4B2');
        $this->addSql('DROP TABLE answer');
        $this->addSql('DROP TABLE answer_session');
        $this->addSql('DROP TABLE choice');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE questionnaire');
    }
}
